import type { Classification, Confidence, Severity } from '../core/types.js';

export type RuleType = 'unit' | 'api' | 'e2e' | 'parser';

export interface RuleDefinition {
  readonly id: string;
  readonly type: RuleType;
  readonly classification: Classification;
  readonly severity: Severity;
  readonly confidence: Confidence;
  readonly description: {
    readonly en: string;
    readonly zh: string;
  };
  readonly evidenceBoundary: {
    readonly en: string;
    readonly zh: string;
  };
}

function rule(
  id: string,
  type: RuleType,
  classification: Classification,
  severity: Severity,
  description: string,
  descriptionZh: string,
  evidenceBoundary: string,
  evidenceBoundaryZh: string,
): RuleDefinition {
  return {
    id,
    type,
    classification,
    severity,
    confidence: 'HIGH',
    description: { en: description, zh: descriptionZh },
    evidenceBoundary: { en: evidenceBoundary, zh: evidenceBoundaryZh },
  };
}

export const RULE_CATALOG: readonly RuleDefinition[] = [
  rule(
    'UT001',
    'unit',
    'FAKE',
    'CRITICAL',
    'Unit callback has no recognized expect or Node native assert call.',
    'Unit 回调中没有可识别的 expect 或 Node 原生 assert 调用。',
    'An assertion-free callback may still have value through another mechanism.',
    '没有断言的回调可能通过其他机制产生价值。',
  ),
  rule(
    'UT002',
    'unit',
    'FAKE',
    'CRITICAL',
    'Matcher or Node native comparison assertion compares the same primitive literal on both sides.',
    'matcher 或 Node 原生比较断言两侧比较相同的基本字面量。',
    'The finding is limited to identical literal syntax.',
    '该发现仅限于语法完全相同的字面量。',
  ),
  rule(
    'UT003',
    'unit',
    'FAKE',
    'CRITICAL',
    'Matcher or Node native comparison assertion compares an expression with identical structural text.',
    'matcher 或 Node 原生比较断言将表达式与结构完全相同的文本比较。',
    'Semantically equivalent but differently written expressions are not inferred.',
    '不会推断写法不同但语义等价的表达式。',
  ),
  rule(
    'UT004',
    'unit',
    'WEAK',
    'WARNING',
    'Every direct assertion only checks zero-argument existence or truthiness.',
    '所有直接断言只检查无参数的存在性或真值。',
    'Existence or truthiness may be the intended unit contract.',
    '存在性或真值可能就是预期的单元契约。',
  ),
  rule(
    'UT008',
    'unit',
    'FAKE',
    'CRITICAL',
    'Catch block is empty or only logs to console.',
    'catch 块为空或只向 console 日志。',
    'Catch blocks with other work are outside this rule.',
    '包含其他操作的 catch 块不属于此规则。',
  ),
  rule(
    'UT011',
    'unit',
    'FAKE',
    'CRITICAL',
    'Matcher or Node native comparison assertion calls the same callee with structurally identical arguments on both sides.',
    'matcher 或 Node 原生比较断言两侧调用相同 callee 且参数结构相同。',
    'The rule does not judge two-call comparisons with different arguments.',
    '不会判断参数不同的双调用比较。',
  ),
  rule(
    'UT012',
    'unit',
    'FAKE',
    'CRITICAL',
    'Callback contains a bare expect call without a matcher.',
    '回调包含没有 matcher 的裸 expect 调用。',
    'The rule reports the missing recognizable assertion, not missing side effects.',
    '该规则报告缺少可识别断言，不判断是否缺少副作用。',
  ),
  rule(
    'UT013',
    'unit',
    'FAKE',
    'CRITICAL',
    'expect.assertions(0) appears with an actual matcher.',
    'expect.assertions(0) 与实际 matcher 同时出现。',
    'Only the explicit zero-count contradiction is reported.',
    '仅报告明确的零计数矛盾。',
  ),
  rule(
    'UT014',
    'unit',
    'WEAK',
    'WARNING',
    'Every direct assertion only verifies mock interaction.',
    '所有直接断言只验证 mock 交互。',
    'Interaction assertions may be valid; business sufficiency is not inferred.',
    '交互断言可能有效，不推断其业务充分性。',
  ),
  rule(
    'UT015',
    'unit',
    'WEAK',
    'WARNING',
    'Every direct assertion only uses a snapshot matcher.',
    '所有直接断言只使用 snapshot matcher。',
    'Snapshots may be valid regression contracts.',
    'snapshot 可能是有效的回归契约。',
  ),
  rule(
    'API001',
    'api',
    'WEAK',
    'WARNING',
    'Every recognized assertion only checks response status.',
    '所有可识别断言只检查 response 状态。',
    'Status-only may be sufficient for a specific endpoint.',
    '仅状态码对特定 endpoint 可能足够。',
  ),
  rule(
    'API002',
    'api',
    'WEAK',
    'WARNING',
    'Every direct assertion only checks response body or data existence.',
    '所有直接断言只检查 response body 或 data 存在。',
    'Body/data existence may be an intentional minimum contract.',
    'body/data 存在可能是有意设计的最低契约。',
  ),
  rule(
    'API003',
    'api',
    'WEAK',
    'WARNING',
    'Every direct assertion only checks that the response object exists.',
    '所有直接断言只检查 response 对象存在。',
    'Schema and business state are not inferred.',
    '不会推断 schema 或业务状态。',
  ),
  rule(
    'API004',
    'api',
    'WEAK',
    'WARNING',
    'Every response body or data assertion directly echoes a request-like value.',
    '所有响应 body 或 data 断言都直接回显 request-like 值。',
    'Only declared request-like names and properties are recognized.',
    '仅识别明确声明的 request-like 名称和属性。',
  ),
  rule(
    'API005',
    'api',
    'WEAK',
    'WARNING',
    'Every body or data assertion only checks property presence.',
    '所有 body 或 data 断言只检查属性存在。',
    'Property presence may be a valid minimum schema check.',
    '属性存在可能是有效的最低 schema 检查。',
  ),
  rule(
    'API006',
    'api',
    'WEAK',
    'WARNING',
    'Every assertion only checks response headers existence.',
    '所有断言只检查 response headers 存在。',
    'Header existence is not treated as endpoint correctness.',
    '不会把 header 存在解释为 endpoint 正确。',
  ),
  rule(
    'API007',
    'api',
    'WEAK',
    'WARNING',
    'Every assertion only checks response content-type or metadata.',
    '所有断言只检查 response content-type 或元数据。',
    'Metadata does not prove body or business state.',
    '元数据不证明 body 或业务状态。',
  ),
  rule(
    'API008',
    'api',
    'WEAK',
    'WARNING',
    'Every assertion only checks response request method or URL metadata.',
    '所有断言只检查 response request 的 method 或 URL 元数据。',
    'Transport checks are not interpreted as business verification.',
    '不会把 transport 检查解释为业务验证。',
  ),
  rule(
    'API009',
    'api',
    'WEAK',
    'WARNING',
    'Every body or data assertion only checks an empty or zero-length result.',
    '所有 body 或 data 断言只检查空结果或零长度。',
    'An empty result may be a valid business outcome.',
    '空结果可能是合法业务结果。',
  ),
  rule(
    'API010',
    'api',
    'FAKE',
    'CRITICAL',
    'API request error is swallowed by an empty or console-only catch.',
    'API 请求错误被空 catch 或 console-only catch 吞掉。',
    'Only deterministic swallowed-error syntax is reported.',
    '仅报告确定性的吞异常语法。',
  ),
  rule(
    'E2E001',
    'e2e',
    'FAKE',
    'CRITICAL',
    'Playwright test callback has no recognized expect assertion.',
    'Playwright 测试回调中没有可识别的 expect 断言。',
    'Action-only journeys may still be setup or exploration.',
    '只有操作的流程可能仍用于准备或探索。',
  ),
  rule(
    'E2E002',
    'e2e',
    'WEAK',
    'WARNING',
    'Every recognized Playwright assertion checks only the page URL.',
    '所有可识别的 Playwright 断言只检查页面 URL。',
    'URL-only may be sufficient for a specific journey.',
    '仅 URL 对特定流程可能足够。',
  ),
  rule(
    'E2E003',
    'e2e',
    'WEAK',
    'WARNING',
    'Every direct Playwright assertion only checks element visibility.',
    '所有直接 Playwright 断言只检查元素可见性。',
    'Visibility may be the intended journey outcome.',
    '可见性可能就是预期的流程结果。',
  ),
  rule(
    'E2E004',
    'e2e',
    'WEAK',
    'WARNING',
    'page.waitForTimeout receives a numeric literal.',
    'page.waitForTimeout 使用了数字字面量。',
    'Variables and external-system requirements are not inferred.',
    '不会推断变量等待或外部系统要求。',
  ),
  rule(
    'E2E005',
    'e2e',
    'WEAK',
    'WARNING',
    'Selector literal relies on an unstable CSS, tag, ID, XPath, or structure form.',
    'selector 字面量依赖不稳定的 CSS、tag、ID、XPath 或结构形式。',
    'Stable role, label, and test-id selectors are outside the rule.',
    '稳定的 role、label 和 test-id selector 不属于此规则。',
  ),
  rule(
    'E2E006',
    'e2e',
    'FAKE',
    'CRITICAL',
    'Playwright journey error is swallowed by an empty or console-only catch.',
    'Playwright 流程错误被空 catch 或 console-only catch 吞掉。',
    'Cleanup semantics are not inferred beyond the syntax.',
    '不会超出语法推断 cleanup 语义。',
  ),
  rule(
    'E2E007',
    'e2e',
    'WEAK',
    'WARNING',
    'Expect assertion is located inside a conditional branch.',
    'expect 断言位于条件分支中。',
    'The condition may be valid; only path coverage is questioned.',
    '条件可能合理；该规则只提示路径覆盖问题。',
  ),
  rule(
    'E2E008',
    'e2e',
    'FAKE',
    'CRITICAL',
    'Direct Playwright matcher expression is not awaited.',
    '直接 Playwright matcher 表达式没有 await。',
    'Promise.all and custom wrappers are outside this direct-call rule.',
    'Promise.all 和自定义封装不属于此直接调用规则。',
  ),
  rule(
    'E2E009',
    'e2e',
    'WEAK',
    'WARNING',
    'Explicit Playwright page action is not awaited.',
    '明确的 Playwright page action 没有 await。',
    'Only the declared page action method list is recognized.',
    '仅识别声明过的 page action 方法列表。',
  ),
  rule(
    'E2E010',
    'e2e',
    'WEAK',
    'WARNING',
    'Every direct assertion only checks empty text or an empty attribute.',
    '所有直接断言只检查空文本或空属性。',
    'An empty state may be a valid journey outcome.',
    '空状态可能是合法流程结果。',
  ),
  rule(
    'PARSER001',
    'parser',
    'INVALID',
    'WARNING',
    'TypeScript reports a parser diagnostic for a selected test file.',
    'TypeScript 为选中的测试文件报告 parser 诊断。',
    'Parser syntax evidence is not runtime validity evidence.',
    '源码语法证据不等于运行时有效性证据。',
  ),
] as const;

export function getRuleDefinition(ruleId: string): RuleDefinition | undefined {
  return RULE_CATALOG.find((definition) => definition.id === ruleId);
}

export function supportedRuleIds(): readonly string[] {
  return RULE_CATALOG.map((definition) => definition.id);
}
